IF(NOT WIN32)
	STRING(ASCII 27 Esc)
	SET(ColourReset "${Esc}[m")
	SET(BoldRed "${Esc}[1;31m")
	SET(BoldGreen "${Esc}[1;32m")
	SET(BoldYellow "${Esc}[1;33m")
	SET(BoldBlue "${Esc}[1;34m")
	SET(BoldMagenta "${Esc}[1;35m")
	SET(BoldCyan "${Esc}[1;36m")
ENDIF()