if(NOT WIN32)
	string(ASCII 27 Esc)
	set(ColourReset "${Esc}[m")
	set(BoldRed "${Esc}[1;31m")
	set(BoldGreen "${Esc}[1;32m")
	set(BoldYellow "${Esc}[1;33m")
	set(BoldBlue "${Esc}[1;34m")
	set(BoldMagenta "${Esc}[1;35m")
	set(BoldCyan "${Esc}[1;36m")
endif()